[FIREBASE]
type = "service_account"
project_id = "universitymanagementsyst-7a655"
private_key_id = "f2e1b6f0ff82e0faf318430b2c3febb7587e6755"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCaKOpO/LrMsq6U
xlNUYl3LnbBM1TbaHN42S6vxqwbqa5OpHCYaA7Da4fnEsBcgCJxM8wr37MwgsVFL
StLxhO2Iva2YY+82lXGgOcq5DEuPK/9KJnhBDDyIni4U1ADE/yN8T8HcuB+hB10w
PjPmDZ8EcvecqmHCVSx4jC39JZH8NGtuJal1p+yc4TU5DGCLLw9V2f2XzvT+X1br
pYbrDIj74GiZp+bkglmwOt+mq1kBGAkw+whMa3nNA3t84tVdhvkJgkXnUkK/LKIc
pf/o/YNwKKOi7SsnQdVOpXKXuA3b4stvy/aJBjnaVG/lhUtF9LOwYdTlnWqgTtCG
U+7gZwtDAgMBAAECggEAMnRot6Bk3QEwPXYpqMknDLDYFlWERd/D5L5gkNCai1fZ
NLSHTeVeWU0zi6ncb7oRueej89/3MU4Hnt5m6vBINARskB9JGDLSRRAVJvp8smfC
frjXi+ae21H2IBABDni42wNZnk1O4MvBtrvtDYLwxCqCmy5yn4Fz9CJhHOTSgln9
px4fRR0ZfXWX6anuALFRJzjCqVrTFQv5kMxevLn9NV2c+JpU/up8R1TWcYMDCzV+
DuoqUtmvAKzEf5tm7o4yZBfdd/50QmyrWRzmDfEFAd4F/3AGKm3BOwEXV8LF0MXH
pbQBhhcQLqO9gHEue/mJCB+p3onIGyRUsqTUf89W5QKBgQDMHks9bDVauKVy2GxT
jfyFzjWRAgjOwUyevfhfye7Mu2Xr5fWjNdfKt5rDSQb+07gPi/eopYYd9q+1pEOY
7uvnEMK9uMCpKFJMj5W5Zbqa2d/QxSj9gYyU5XVZAaHmWB/UGGKD0GUYpIMi4Inu
trGoUh8LbhDh88wKRLZsYnxJZwKBgQDBV+NeX91SQ+pYnL5kvWCJXkbNJlxhzsfw
de6Dtsvft+6g7x39FXBX2HcUt51W+2QBimtXtwgv1aNDjyOsJO3sdmKNMLlUHfVB
nb7rH0+MX18Bq31lgPL6QoCv3JvwXlIAlFB+ytXRzd7besKls5Ls4+gkAnDa2Opx
oB3JF3yZxQKBgQCqQPpxGTjHmwwlZu+0IdJnqUB020WNbx4BqmLpQv20NvskcIMa
x2Ze6BZmnRsAoof8L7s7KBVeGM0mrQTVIzQRX6GPrfLFJaS/x2QTaA7l6qUM9ebi
zJP9/gaLXxkzkH274zsIx2IL0+ytwqxKOIim5RiP6Bac4UVnqzid3ufcMQKBgCYs
wEwGCaEQn9jXOhCSA9mbr8cZ5+u39GpaHroLAb4uhwNnszghX4k4yGpixsJB6MEV
H5S2Ivuu5wmT3atDr2adCWBvWmhtcdt+1g9+oypIOm4N+jhseY1ITDhtCq0vMmnC
3xHp4sYGLBaR6pTlHAGCDnfts3LCmafNwZPO+18xAoGAGPgizu7LKzWRI2RRJv61
YH/gsoFtwrxykPGg6Tgxynba8XiuXTYY2Ocod9YQYpf38vs7mIAdUUxf1Kac/k/i
eUYCX0vPvodqa5JakJEVnViY04KJF+Ayszx54EaRC5qwsrS22NaFWQeMzTLH8Vt2
AeuvnBBfgO2g1xqHu+yFfJ8=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@universitymanagementsyst-7a655.iam.gserviceaccount.com"
client_id = "109091322885644323505"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40universitymanagementsyst-7a655.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
